Fix error when executing multi-model ReplayMachine
Prior to this commit, executing a multi-model ReplayMachine ran into the
following error as soon as the execution left the first model:

org.graphwalker.core.machine.MachineException: No path generator is defined