Fix for NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
When starting Studio it fails loading org/slf4j/impl/StaticLoggerBinder
due to chaneges in sping from version 2.7.8

See:
* https://github.com/spring-projects/spring-boot/issues/12649#issuecomment-2086678117
* https://docs.spring.io/spring-boot/docs/2.7.8/reference/html/features.html#features.logging