Add replayMultiModelMachine test exposing a bug
Currently, executing ReplayMachine with a multi-model machine runs into
this error as soon as the execution leaves the initial model:

org.graphwalker.core.machine.MachineException: No path generator is defined